title: Mahidul Haque  # name of the site
author: mahidulhq # name of site's author
email:  # email of site's author
url: https://mahidulhq.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Welcome to my corner of the web. I'm a tech guy based in Sylhet, Bangladesh. Here, you'll find my projects, writing, insights, and ways to connect.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

social:
  name: Mahidul Haque
  links:
    - https://twitter.com/mahidulhq
    - https://www.facebook.com/mahidulhq
    - https://www.linkedin.com/in/mahidulhq
    - https://github.com/mahidulhq

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: 'G-DT040K4BMP'  # Your GA4 measurement ID
    anonymizeIp: true

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
